export enum QueryKeys {
  AUTH = "auth",
  SIGN_UP = "sign-up",
  SIGN_IN = "sign-in",
  SIGN_OUT = "sign-out",
  CURRENT_USER = "current-user",
  USERS = "users",
  POSTS = "posts",
  COMMENTS = "comments",
  USER = "user",
  UPDATE_USER = "update-user",
  LESSON_PLAN = "lesson-plan",
  CREATE_LESSON_PLAN = "create-lesson-plan",
  FAVORITES = "favorites",
  ADD_FAVORITE = "add-favorite",
  UPDATE_LESSON_PLAN = "update-lesson-plan",
  REMOVE_FAVORITE = "remove-favorite",
}
