import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "../providers/query.provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "ClasPlanner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          {children}
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
