name: ClassPlanner Server CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: server/server/package-lock.json

      - name: Install dependencies
        run: |
          cd server/server
          npm ci

      - name: Run database migrations
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          cd server/server/src
          npx prisma migrate deploy

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSHUB_PASS }}

      - name: Build Docker image
        run: |
          docker build ./server/server -f ./server/server/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/classplanner-server:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/classplanner-server:latest